from .nodes import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_2,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_2,
)

from .HumoAutomation import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_3,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_3,
)

from .HumoAutomationExtra1 import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_4,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_4,
)

from .HumoAutomationExtra2 import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_5,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_5,
)

# 🆕 ADD THIS LINE
from .GeneralVideoNodes import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_6,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_6,
)

from .GeneralVideoNodes2 import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_7,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_7,
)

NODE_CLASS_MAPPINGS = {
    **NODE_CLASS_MAPPINGS_2,
    **NODE_CLASS_MAPPINGS_3,
    **NODE_CLASS_MAPPINGS_4,
    **NODE_CLASS_MAPPINGS_5,
    **NODE_CLASS_MAPPINGS_6,
    **NODE_CLASS_MAPPINGS_7, 
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **NODE_DISPLAY_NAME_MAPPINGS_2,
    **NODE_DISPLAY_NAME_MAPPINGS_3,
    **NODE_DISPLAY_NAME_MAPPINGS_4,
    **NODE_DISPLAY_NAME_MAPPINGS_5,
    **NODE_DISPLAY_NAME_MAPPINGS_6,
    **NODE_DISPLAY_NAME_MAPPINGS_7,
}

WEB_DIRECTORY = "./web"

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
]
