const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const {test}=require('node:test');const s=fs.readFileSync(path.join(__dirname,'../web/VRGDG_MusicVideoBuilderUI.js'),'utf8');
const code=s.slice(s.indexOf('  function miniMaxPromptReferenceSignature'),s.indexOf('  async function runMiniMaxH3PromptGeneration'));
function fixture(){const segment={id:'a'};const c={segment,items:[{kind:'subject',source_id:'lead',label:'Lead',image:{path:'lead.png'}},{kind:'location',source_id:'room',label:'Room',image:{path:'room.png'}}],miniMaxH3ModeForSegment:()=> 'reference_to_video',miniMaxOrderedImageReferenceItemsForSegment:()=>c.items,miniMaxH3ImageReferencePromptItems:()=>c.items,allEditableSegments:()=>[segment]};vm.createContext(c);vm.runInContext(code,c);return c;}
test('generated prompt retains ordered bindings through session serialization',()=>{const c=fixture();c.rememberMiniMaxPromptReferences(c.segment,'prompt',c.miniMaxPromptReferenceSignature(c.segment));const loaded=JSON.parse(JSON.stringify(c.segment));assert.equal(c.miniMaxPromptReferenceStatus(loaded,'prompt','reference_to_video'),'');});
for(const change of ['reorder','add','remove','path','name','description'])test(`reference ${change} marks saved prompt stale`,()=>{const c=fixture();c.rememberMiniMaxPromptReferences(c.segment,'prompt',c.miniMaxPromptReferenceSignature(c.segment));if(change==='reorder')c.items.reverse();if(change==='add')c.items.push({kind:'subject',label:'Extra'});if(change==='remove')c.items.pop();if(change==='path')c.items[0].image.path='replacement.png';if(change==='name')c.items[0].label='New name';if(change==='description')c.items[0].description='new identity';assert.match(c.miniMaxPromptReferenceStatus(c.segment,'prompt','reference_to_video'),/References changed/);});
test('legacy and manually edited prompts require review, not automatic rewriting',()=>{const c=fixture();assert.match(c.miniMaxPromptReferenceStatus(c.segment,'old prompt','reference_to_video'),/not been verified/);c.rememberMiniMaxPromptReferences(c.segment,'old prompt',c.miniMaxPromptReferenceSignature(c.segment));assert.match(c.miniMaxPromptReferenceStatus(c.segment,'edited prompt','reference_to_video'),/not been verified/);assert.equal(c.segment.minimax_h3_prompt_reference_binding.prompt,'old prompt');});
test('review records actual paths and detects a changed render list',()=>{const c=fixture();c.rememberMiniMaxPromptReferences(c.segment,'p',c.miniMaxPromptReferenceSignature(c.segment),['one.png']);assert.equal(c.miniMaxPromptReferenceStatus(c.segment,'p','reference_to_video',['one.png']),'');assert.match(c.miniMaxPromptReferenceStatus(c.segment,'p','reference_to_video',['two.png']),/different reference/);});
test('non-reference modes do not require a reference review',()=>{const c=fixture();assert.equal(c.miniMaxPromptReferenceStatus(c.segment,'p','text_to_video'),'');});
test('signature is compact for in-memory images',()=>{const c=fixture();c.items[0].image={data:'x'.repeat(100000)};assert.ok(c.miniMaxPromptReferenceSignature(c.segment).length<40);});
test('declining render reference review stops before workflow generation',async()=>{const c=fixture();Object.assign(c,{segment:c.segment,prompt:'legacy',mode:'reference_to_video',imagePaths:['lead.png'],options:{},sceneIndex:0,sceneDisplayName:()=> 'Scene 1',window:{confirm:()=>false},autoSaveSessionQuiet:async()=>{throw Error('should not save');}});const a=s.indexOf('    const referenceStatus = miniMaxPromptReferenceStatus(segment, prompt, mode, imagePaths);');const b=s.indexOf('    let continuityImageNumber',a);vm.runInContext('async function check(){'+s.slice(a,b)+'}',c);await assert.rejects(c.check(),/Render cancelled/);});
