from .nodes import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_2, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_2

# Merge all mappings
NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS_2}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS_2}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
